export default color => ({
  heading1: { color: color, fontFamily: 'Lacquer-Regular' },
  heading2: { color: color, fontFamily: 'Lacquer-Regular' },
  heading3: { color: color, fontFamily: 'Lacquer-Regular' },
  heading4: { color: color, fontFamily: 'Lacquer-Regular' },
  heading5: { color: color, fontFamily: 'Lacquer-Regular' },
  heading6: { color: color, fontFamily: 'Lacquer-Regular' },
  hr: { color: color },
  strong: { color: color },
  em: { color: color },
  s: { color: color },
  blockquote: { color: color },
  bullet_list: { color: color },
  ordered_list: { color: color },
  list_item: { color: color },
  code_inline: { color: color },
  code_block: { color: color },
  fence: { color: color },
  table: { color: color, borderColor: color },
  thead: { color: color, borderColor: color },
  tbody: { color: color, borderColor: color },
  th: { color: color, borderColor: color },
  tr: { color: color, borderColor: color },
  td: { color: color, borderColor: color },
  link: { color: color },
  blocklink: { color: color },
  image: { color: color },
  text: { color: color },
  textgroup: { color: color },
  paragraph: { color: color },
  hardbreak: { color: color },
  softbreak: { color: color },
  pre: { color: color },
  inline: { color: color },
  span: { color: color },
});
