export default Object.freeze({
  CREATE_USER: 'CREATE_USER',
  CREATE_USER_PENDING: 'CREATE_USER_PENDING',
  CREATE_USER_FULFILLED: 'CREATE_USER_FULFILLED',
  CREATE_USER_REJECTED: 'CREATE_USER_REJECTED',

  LOGIN_USER: 'LOGIN_USER',
});
