export default Object.freeze({
  SET_TOKEN: 'SET_TOKEN',
  SET_TOKEN_PENDING: 'SET_TOKEN_PENDING',
  SET_TOKEN_FULFILLED: 'SET_TOKEN_FULFILLED',
  SET_TOKEN_REJECTED: 'SET_TOKEN_REJECTED',

  CHECK_TOKEN: 'CHECK_TOKEN',
  CHECK_TOKEN_PENDING: 'CHECK_TOKEN_PENDING',
  CHECK_TOKEN_FULFILLED: 'CHECK_TOKEN_FULFILLED',
  CHECK_TOKEN_REJECTED: 'CHECK_TOKEN_REJECTED',
});
